# Purge all the forks that weren't updated in the last 60 days.
name: Purge outdated forks


on:
  push:

  # Everyday at 0:37 UTC.
  schedule:
    - cron: "37 0 * * *"


# Cancel any running workflow if the CI gets triggered again.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


env:
  GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub Actions.
  GITHUB_USERNAME: rednafi
  TIMEOUT: 10


jobs:
  set-constants:
    uses: rednafi/cronies/.github/workflows/set-constants.yml@main

  purge-forks:
    needs: ["set-constants"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: cp311
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            **/requirements*.txt

      - run: |
          echo "Cache hit: ${{ steps.cp311.outputs.cache-hit }}"
          echo "Python version $PYTHON_VERSION"
          echo "Python version ${{ env.PYTHON_VERSION }}"

      - name: Install the dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Check linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Run the script
        run: |
          python -m scripts.fork_purger
