name: Purge outdated forks

on:
  push:

  # Everyday at 0:37 UTC.
  schedule:
    - cron: "37 0 * * *"

# Cancel any running workflow if the CI gets triggered again.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

# Grant permissions to delete forks.
permissions: write-all

env:
  # Globally set in the repo settings.
  GH_TOKEN: ${{ secrets.GH_TOKEN }} # Implicitly used by the script.
  GO_VERSION: "1.21"

  # Local env vars.
  GH_USERNAME: rednafi
  TIMEOUT: 10

jobs:
  purge-forks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
          cache-dependency-path: go.sum

      - name: Install dependencies
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go get -v -t -d ./...

      - name: Lint
        run: golangci-lint run ./...

      - name: Run script
        run: go run scripts/fork_purger.go
