# Purge all the forks that weren't updated in the last 60 days.
name: Purge outdated forks

on:
  push:

  # Everyday at 0:37 UTC.
  schedule:
    - cron: "37 0 * * *"


# Cancel any running workflow if the CI gets triggered again.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}} # Provided by GitHub Actions.
  GITHUB_USERNAME: rednafi
  TIMEOUT: 10

jobs:
  install-deps:
    uses: rednafi/cronies/.github/workflows/dep-installer.yml@main

  purge-forks:
    needs: ["install-deps"]
    runs-on: ubuntu-latest
    steps:
      steps:
      - uses: actions/checkout@v3

      - name: Check linter
        run: |
          echo "Checking linter conformity..."
          make lint-check

      - name: Run the script
        run: |
          python -m scripts.fork_purger
